#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

# Auto-tune recommendations for llama.cpp server on constrained devices.
# Writes ~/.local/openwebui-llamacpp/config.env with conservative, reproducible defaults.

ROUTER_DIR="${ROUTER_DIR:-${HOME}/.local/openwebui-llamacpp}"
CONFIG_FILE="${ROUTER_DIR}/config.env"
mkdir -p "${ROUTER_DIR}"

# Detect memory (kB)
mem_kb=0
if [ -r /proc/meminfo ]; then
  mem_kb=$(awk '/MemTotal:/ {print $2}' /proc/meminfo || echo 0)
fi

# Detect CPU cores
cpu_cores=1
if command -v nproc >/dev/null 2>&1; then
  cpu_cores=$(nproc --all || echo 1)
elif [ -r /proc/cpuinfo ]; then
  cpu_cores=$(grep -c '^processor' /proc/cpuinfo || echo 1)
fi

# Determine defaults based on memory
# thresholds (in kB): small < 3.5GB (3500000), medium < 6GB (6000000)
if [ "$mem_kb" -gt 0 ] && [ "$mem_kb" -lt 3500000 ]; then
  # very constrained device
  LLAMA_THREADS=1
  LLAMA_THREADS_BATCH=1
  LLAMA_FIT=on
  LLAMA_FIT_TARGET=128
  LLAMA_NO_MMAP=1
elif [ "$mem_kb" -lt 6000000 ]; then
  # modest device
  LLAMA_THREADS=1
  LLAMA_THREADS_BATCH=1
  LLAMA_FIT=on
  LLAMA_FIT_TARGET=256
  LLAMA_NO_MMAP=0
else
  # more capable
  LLAMA_THREADS=2
  LLAMA_THREADS_BATCH=2
  LLAMA_FIT=on
  LLAMA_FIT_TARGET=1024
  LLAMA_NO_MMAP=0
fi

# Adjust threads downward if CPU has few cores
if [ "$cpu_cores" -le 2 ]; then
  LLAMA_THREADS=1
  LLAMA_THREADS_BATCH=1
fi

# Common extra args to reduce memory footprint: set conservative context size to reduce KV cache
# and avoid passing unsupported flags.
LLAMA_EXTRA_ARGS="--ctx-size 2048"

# Write config
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by scripts/15-auto-tune-llamacpp.sh
# Tune values for constrained device. Override by editing or exporting env vars before starting.
export LLAMA_THREADS=${LLAMA_THREADS}
export LLAMA_THREADS_BATCH=${LLAMA_THREADS_BATCH}
export LLAMA_FIT=${LLAMA_FIT}
export LLAMA_FIT_TARGET=${LLAMA_FIT_TARGET}
export LLAMA_NO_MMAP=${LLAMA_NO_MMAP}
export LLAMA_EXTRA_ARGS='${LLAMA_EXTRA_ARGS}'
EOF

printf "Wrote config to %s\n" "$CONFIG_FILE"
printf "Detected: mem_kb=%s cpu_cores=%s\n" "$mem_kb" "$cpu_cores"
printf "Recommended: LLAMA_THREADS=%s LLAMA_FIT_TARGET=%s LLAMA_NO_MMAP=%s\n" "$LLAMA_THREADS" "$LLAMA_FIT_TARGET" "$LLAMA_NO_MMAP"

# Print the config for confirmation
cat "$CONFIG_FILE"

# Exit success
exit 0
