#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

# Auto-tune recommendations for llama.cpp server on constrained devices.
# Writes ~/.local/llamacpp/config.env with conservative, reproducible defaults.

LLAMACPP_HOME="${LLAMACPP_HOME:-${ROUTER_DIR:-${HOME}/.local/llamacpp}}"
ROUTER_DIR="${LLAMACPP_HOME}"
CONFIG_FILE="${LLAMACPP_HOME}/config.env"
mkdir -p "${LLAMACPP_HOME}"

# Detect memory (kB)
mem_kb=0
if [ -r /proc/meminfo ]; then
  mem_kb=$(awk '/MemTotal:/ {print $2}' /proc/meminfo || echo 0)
fi

# Detect CPU cores
cpu_cores=1
if command -v nproc >/dev/null 2>&1; then
  cpu_cores=$(nproc --all || echo 1)
elif [ -r /proc/cpuinfo ]; then
  cpu_cores=$(grep -c '^processor' /proc/cpuinfo || echo 1)
fi

# Determine defaults based on memory.
# This device has ~5.5 GiB RAM and can easily OOM when router mode auto-loads a model
# with default ctx/parallel/warmup settings, so prefer conservative memory-first defaults.
if [ "$mem_kb" -gt 0 ] && [ "$mem_kb" -lt 3500000 ]; then
  LLAMA_THREADS=1
  LLAMA_THREADS_BATCH=1
  LLAMA_NO_MMAP=1
  LLAMA_CTX_SIZE=384
  LLAMA_BATCH_SIZE=64
  LLAMA_UBATCH_SIZE=32
  LLAMA_FIT_TARGET=2048
elif [ "$mem_kb" -lt 7000000 ]; then
  LLAMA_THREADS=1
  LLAMA_THREADS_BATCH=1
  LLAMA_NO_MMAP=0
  LLAMA_CTX_SIZE=256
  LLAMA_BATCH_SIZE=64
  LLAMA_UBATCH_SIZE=32
  LLAMA_FIT_TARGET=2304
else
  LLAMA_THREADS=3
  LLAMA_THREADS_BATCH=2
  LLAMA_NO_MMAP=0
  LLAMA_CTX_SIZE=1024
  LLAMA_BATCH_SIZE=256
  LLAMA_UBATCH_SIZE=128
  LLAMA_FIT_TARGET=1024
fi

if [ "$cpu_cores" -le 2 ]; then
  LLAMA_THREADS=1
  LLAMA_THREADS_BATCH=1
fi

LLAMA_COMMON_ARGS=""
LLAMA_ROUTER_ARGS="--parallel 1 --models-max 1 --ctx-size ${LLAMA_CTX_SIZE} --batch-size ${LLAMA_BATCH_SIZE} --ubatch-size ${LLAMA_UBATCH_SIZE} --fit on --fit-target ${LLAMA_FIT_TARGET} --fit-ctx ${LLAMA_CTX_SIZE} --no-warmup --threads-http 1"
LLAMA_SERVER_ARGS="--ctx-size ${LLAMA_CTX_SIZE} --batch-size ${LLAMA_BATCH_SIZE} --ubatch-size ${LLAMA_UBATCH_SIZE} --fit on --fit-target ${LLAMA_FIT_TARGET} --fit-ctx ${LLAMA_CTX_SIZE} --no-warmup --threads-http 1"
LLAMA_CLI_ARGS="--ctx-size ${LLAMA_CTX_SIZE} --batch-size ${LLAMA_BATCH_SIZE} --ubatch-size ${LLAMA_UBATCH_SIZE} --no-warmup"

# Write config
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by scripts/15-auto-tune-llamacpp.sh
# Tune values for constrained device. Override by editing or exporting env vars before starting.
export LLAMA_THREADS=${LLAMA_THREADS}
export LLAMA_THREADS_BATCH=${LLAMA_THREADS_BATCH}
export LLAMA_NO_MMAP=${LLAMA_NO_MMAP}
export LLAMA_CTX_SIZE=${LLAMA_CTX_SIZE}
export LLAMA_BATCH_SIZE=${LLAMA_BATCH_SIZE}
export LLAMA_UBATCH_SIZE=${LLAMA_UBATCH_SIZE}
export LLAMA_FIT_TARGET=${LLAMA_FIT_TARGET}
export LLAMA_COMMON_ARGS='${LLAMA_COMMON_ARGS}'
export LLAMA_ROUTER_ARGS='${LLAMA_ROUTER_ARGS}'
export LLAMA_SERVER_ARGS='${LLAMA_SERVER_ARGS}'
export LLAMA_CLI_ARGS='${LLAMA_CLI_ARGS}'
EOF

printf "Wrote config to %s\n" "$CONFIG_FILE"
printf "Detected: mem_kb=%s cpu_cores=%s\n" "$mem_kb" "$cpu_cores"
printf "Recommended: LLAMA_THREADS=%s LLAMA_CTX_SIZE=%s LLAMA_BATCH_SIZE=%s LLAMA_FIT_TARGET=%s\n" "$LLAMA_THREADS" "$LLAMA_CTX_SIZE" "$LLAMA_BATCH_SIZE" "$LLAMA_FIT_TARGET"

# Print the config for confirmation
cat "$CONFIG_FILE"

# Exit success
exit 0
