services:
  termux:
    image: termux/termux-docker:aarch64
    ports:
      - 8022:8022
    volumes:
      - ./setup:/data/data/com.termux/files/home/setup
    environment:
      - TERMUX_UID=1000
      - TERMUX_GID=1000
    stdin_open: true # Enable reading from the standard input
    tty: true # Allocate a pseudo-TTY
    command: TERM=xterm-256color /bin/bash
