services:
  termux:
    image: termux/termux-docker:latest
    ports:
      # ===================================================================== #
      - "4510-4559:4510-4559"
    volumes:
      - ./setup:/data/data/com.termux/files/home/setup
    working_dir: /data/data/com.termux/files/home/setup
    stdin_open: true # Enable reading from the standard input
    tty: true # Allocate a pseudo-TTY
    command: TERM=xterm-256color /bin/bash
